# Generated by Django 5.0.4 on 2024-05-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='fulfillment_rate',
            new_name='fulfilment_rate',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='acknowledgment_date',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='issue_date',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='quality_rating',
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='items',
            field=models.TextField(),
        ),
    ]
